### ISSUE TITLE
Call to a member function createSetupIntent() on null 

### ISSUE THREAD

**Issue by twd3** [silentzco/statamic-charge#14]
When trying to render the form using the sample I get:
```
Call to a member function createSetupIntent() on nullC:\_statamic\ma\resources\views/join.antlers.html#0Facade\Ignition\Exceptions\ViewException
    Call to a member function createSetupIntent() on nullC:\_statamic\ma\vendor\silentz\charge\src\Tags\Subscription.php#9Error

    {
        public function setupIntent(): string
        {
            return current_user()->createSetupIntent()->client_secret;
        }
        public function create(): string

    #0 [internal function]: Silentz\Charge\Tags\Subscription->setupIntent()
    #1 C:\_statamic\ma\vendor\statamic\cms\src\View\Antlers\Engine.php(152): call_user_func(Array)
    #2 [internal function]: Statamic\View\Antlers\Engine::renderTag(Object(Statamic\View\Antlers\Parser), 'subscription', Array, '', Array)
    #3 C:\_statamic\ma\vendor\statamic\cms\src\View\Antlers\Parser.php(575): call_user_func_array(Array, Array)
    #4 C:\_statamic\ma\vendor\statamic\cms\src\View\Antlers\Parser.php(176): Statamic\View\Antlers\Parser->parseCallbackTags(' <input type...', Array)
    #5 C:\_statamic\ma\vendor\statamic\cms\src\View\Antlers\Antlers.php(29): Statamic\View\Antlers\Parser->parse(' <input type...', Array)
    #6 C:\_statamic\ma\vendor\statamic\cms\src\Tags\Tags.php(149): Statamic\View\Antlers\Antlers->parse('\r\n <input ty...', Array)
    #7 C:\_statamic\ma\vendor\statamic\cms\src\View\Antlers\Antlers.php(20): Statamic\Tags\Tags->Statamic\Tags\{closure}(Object(Statamic\View\Antlers\Antlers))
    #8 C:\_statamic\ma\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php(261): Statamic\View\Antlers\Antlers->usingParser(Object(Statamic\View\Antlers\Parser), Object(Closure))
    #9 C:\_statamic\ma\vendor\statamic\cms\src\Tags\Tags.php(151): Illuminate\Support\Facades\Facade::__callStatic('usingParser', Array)
    #10 C:\_statamic\ma\vendor\silentz\charge\src\Tags\BaseTag.php(21): Statamic\Tags\Tags->parse(Array)
    #11 C:\_statamic\ma\vendor\silentz\charge\src\Tags\Subscription.php(15): Silentz\Charge\Tags\BaseTag->createForm('http://major-ve...')
    #12 [internal function]: Silentz\Charge\Tags\Subscription->create()
    #13 C:\_statamic\ma\vendor\statamic\cms\src\View\Antlers\Engine.php(152): call_user_func(Array)
    #14 [internal function]: Statamic\View\Antlers\Engine::renderTag(Object(Statamic\View\Antlers\Parser), 'subscription', Array, '\r\n <input ty...', Array)
    #15 C:\_statamic\ma\vendor\statamic\cms\src\View\Antlers\Parser.php(575): call_user_func_array(Array, Array)
    #16 C:\_statamic\ma\vendor\statamic\cms\src\View\Antlers\Parser.php(176): Statamic\View\Antlers\Parser->parseCallbackTags('<div class="w-f...', Array)
    #17 C:\_statamic\ma\vendor\statamic\cms\src\View\Antlers\Parser.php(131): Statamic\View\Antlers\Parser->parse('<div class="w-f...', Array)
    #18 C:\_statamic\ma\vendor\statamic\cms\src\View\Antlers\Engine.php(89): Statamic\View\Antlers\Parser->parseView('C:\\_statamic\\ma...', '<div class="w-f...', Array)
    #19 C:\_statamic\ma\vendor\laravel\framework\src\Illuminate\View\View.php(139): Statamic\View\Antlers\Engine->get('C:\\_statamic\\ma...', Array)
    #20 C:\_statamic\ma\vendor\laravel\framework\src\Illuminate\View\View.php(122): Illuminate\View\View->getContents()
    #21 C:\_statamic\ma\vendor\laravel\framework\src\Illuminate\View\View.php(91): Illuminate\View\View->renderContents()
    #22 C:\_statamic\ma\vendor\statamic\cms\src\View\View.php(74): Illuminate\View\View->render()
    #23 C:\_statamic\ma\vendor\statamic\cms\src\Http\Responses\DataResponse.php(144): Statamic\View\View->render()
    #24 C:\_statamic\ma\vendor\statamic\cms\src\Http\Responses\DataResponse.php(45): Statamic\Http\Responses\DataResponse->contents()
    #25 C:\_statamic\ma\vendor\statamic\cms\src\Structures\Page.php(287): Statamic\Http\Responses\DataResponse->toResponse(Object(Illuminate\Http\Request))
    #26 C:\_statamic\ma\vendor\laravel\framework\src\Illuminate\Routing\Router.php(744): Statamic\Structures\Page->toResponse(Object(Illuminate\Http\Request))
    #27 C:\_statamic\ma\vendor\laravel\framework\src\Illuminate\Routing\Router.php(731): Illuminate\Routing\Router::toResponse(Object(Illuminate\Http\Request), Object(Statamic\Structures\Page))
    #28 C:\_statamic\ma\vendor\laravel\framework\src\Illuminate\Routing\Router.php(685): Illuminate\Routing\Router->prepareResponse(Object(Illuminate\Http\Request), Object(Statamic\Structures\Page))
    #29 C:\_statamic\ma\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(128): Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
    #30 C:\_statamic\ma\vendor\statamic\cms\src\StaticCaching\Middleware\Cache.php(29): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
    #31 C:\_statamic\ma\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): Statamic\StaticCaching\Middleware\Cache->handle(Object(Illuminate\Http\Request), Object(Closure))
    #32 C:\_statamic\ma\vendor\statamic\cms\src\Http\Middleware\Localize.php(22): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
    #33 C:\_statamic\ma\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): Statamic\Http\Middleware\Localize->handle(Object(Illuminate\Http\Request), Object(Closure))
    #34 C:\_statamic\ma\vendor\laravel\framework\src\Illuminate\Routing\Middleware\SubstituteBindings.php(41): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
    #35 C:\_statamic\ma\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): Illuminate\Routing\Middleware\SubstituteBindings->handle(Object(Illuminate\Http\Request), Object(Closure))
    #36 C:\_statamic\ma\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\VerifyCsrfToken.php(77): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
    #37 C:\_statamic\ma\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
    #38 C:\_statamic\ma\vendor\laravel\framework\src\Illuminate\View\Middleware\ShareErrorsFromSession.php(49): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
    #39 C:\_statamic\ma\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
    #40 C:\_statamic\ma\vendor\laravel\framework\src\Illuminate\Session\Middleware\StartSession.php(116): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
    #41 C:\_statamic\ma\vendor\laravel\framework\src\Illuminate\Session\Middleware\StartSession.php(62): Illuminate\Session\Middleware\StartSession->handleStatefulRequest(Object(Illuminate\Http\Request), Object(Illuminate\Session\Store), Object(Closure))
    #42 C:\_statamic\ma\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
    #43 C:\_statamic\ma\vendor\laravel\framework\src\Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
    #44 C:\_statamic\ma\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
    #45 C:\_statamic\ma\vendor\laravel\framework\src\Illuminate\Cookie\Middleware\EncryptCookies.php(67): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
    #46 C:\_statamic\ma\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
    #47 C:\_statamic\ma\vendor\statamic\cms\src\StaticCaching\Middleware\Retrieve.php(34): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
    #48 C:\_statamic\ma\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): Statamic\StaticCaching\Middleware\Retrieve->handle(Object(Illuminate\Http\Request), Object(Closure))
    #49 C:\_statamic\ma\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(103): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
    #50 C:\_statamic\ma\vendor\laravel\framework\src\Illuminate\Routing\Router.php(687): Illuminate\Pipeline\Pipeline->then(Object(Closure))
    #51 C:\_statamic\ma\vendor\laravel\framework\src\Illuminate\Routing\Router.php(662): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
    #52 C:\_statamic\ma\vendor\laravel\framework\src\Illuminate\Routing\Router.php(628): Illuminate\Routing\Router->runRoute(Object(Illuminate\Http\Request), Object(Illuminate\Routing\Route))
    #53 C:\_statamic\ma\vendor\laravel\framework\src\Illuminate\Routing\Router.php(617): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
    #54 C:\_statamic\ma\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(165): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
    #55 C:\_statamic\ma\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(128): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
    #56 C:\_statamic\ma\vendor\statamic\cms\src\Http\Middleware\CheckMultisite.php(14): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
    #57 C:\_statamic\ma\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): Statamic\Http\Middleware\CheckMultisite->handle(Object(Illuminate\Http\Request), Object(Closure))
    #58 C:\_statamic\ma\vendor\statamic\cms\src\Http\Middleware\PoweredByHeader.php(19): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
    #59 C:\_statamic\ma\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): Statamic\Http\Middleware\PoweredByHeader->handle(Object(Illuminate\Http\Request), Object(Closure))
    #60 C:\_statamic\ma\vendor\barryvdh\laravel-debugbar\src\Middleware\InjectDebugbar.php(65): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
    #61 C:\_statamic\ma\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): Barryvdh\Debugbar\Middleware\InjectDebugbar->handle(Object(Illuminate\Http\Request), Object(Closure))
    #62 C:\_statamic\ma\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
    #63 C:\_statamic\ma\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle(Object(Illuminate\Http\Request), Object(Closure))
    #64 C:\_statamic\ma\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
    #65 C:\_statamic\ma\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle(Object(Illuminate\Http\Request), Object(Closure))
    #66 C:\_statamic\ma\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\ValidatePostSize.php(27): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
    #67 C:\_statamic\ma\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): Illuminate\Foundation\Http\Middleware\ValidatePostSize->handle(Object(Illuminate\Http\Request), Object(Closure))
    #68 C:\_statamic\ma\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode.php(63): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
    #69 C:\_statamic\ma\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
    #70 C:\_statamic\ma\vendor\fruitcake\laravel-cors\src\HandleCors.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
    #71 C:\_statamic\ma\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): Fruitcake\Cors\HandleCors->handle(Object(Illuminate\Http\Request), Object(Closure))
    #72 C:\_statamic\ma\vendor\fideloper\proxy\src\TrustProxies.php(57): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
    #73 C:\_statamic\ma\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): Fideloper\Proxy\TrustProxies->handle(Object(Illuminate\Http\Request), Object(Closure))
    #74 C:\_statamic\ma\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(103): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
    #75 C:\_statamic\ma\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(140): Illuminate\Pipeline\Pipeline->then(Object(Closure))
    #76 C:\_statamic\ma\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(109): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
    #77 C:\_statamic\ma\public\index.php(55): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
    #78 C:\Users\Duke\AppData\Roaming\Composer\vendor\cretueusebiu\valet-windows\server.php(143): require('C:\\_statamic\\ma...')
    #79 {main}
```

**Comment by edalzell** [comment]
Is the user logged in?

**Comment by twd3** [comment]
No do they have to be?

**Comment by twd3** [comment]
Okay logged in it shows this. It's the three inputs I have in the form. You cant type in them and I was really expecting to see a CC charge thing from Stripe.
![Firefox_Screenshot_2020-09-13T02-29-19 513Z](https://user-images.githubusercontent.com/16004958/93008844-d2174180-f536-11ea-8f86-825c309a80c1.png)

**Comment by edalzell** [comment]
Unrelated to initial issue.  Sounds like you haven't added the Stripe Elements stuff to the page. Please review the Stripe docs to see how to add that: https://stripe.com/docs/stripe-js
